
#run HTTP Request and press Ctrl + Alt + R 

# POST http://localhost:3000/users/signup HTTP/1.1
# content-type: application/json

# {
#  "firstName":"hedra",
#  "lastName":"louka", 
#  "email":"Ha@miu.edu",
#  "password":"123456"
#  }

# POST http://localhost:3000/users/signin HTTP/1.1
# content-type: application/json

# {
#  "email":"Ha@miu.edu",
#  "password":"123456"
#  }


POST http://localhost:3000/users/findbyemail HTTP/1.1
content-type: application/json

{
 "email":"Habdelshahid@miu.edu"
 }